<?php

/**
 * Description of index
 * Conteúdo da página principal
 *
 * @author Felipe Correa Gomes
 * @since 04/07/2019
 * 
 */
class index {
    function conteudo() {
        $conteudo = "<div id='conteudo'>\n"
                . "<span>Teste de conteudo 1</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "<br>\n"
                . "<span>Teste de conteudo 2</span>\n"
                . "</div>\n";
        return $conteudo;
    }
}

//fim da classe index
